project_id = "njgewkqyvxugrozucagq"

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.get-setup-token]
verify_jwt = false

[functions.setup-initial-password]
verify_jwt = false

[functions.send-password-email]
verify_jwt = false
